Development
NextUp-comedy/calcs-nc pull request #28
Opened 2022-07-25 10:10 UTC by zaher-aa

2022-07-25 15:23 UTC, mohanagy requested changes
add .env.example
add Readme.md instructions
improve the validation of the env file

if the steps are correct for running the project in the development mode:
1. npm i
2. npm run build:db
3. npm run migrate:up
4. npm run dev

then there is something missing, the migration command is not working correctly
and the npm run dev command is not working correctly 


References : 
![image](https://user-images.githubusercontent.com/11216054/180815159-6d83aa15-c3cf-4c2f-941a-dbdf5425e369.png)

![image](https://user-images.githubusercontent.com/11216054/180815197-ff02d741-0110-4ecc-8692-8bf9672c9cce.png)


I'm not able to review or test the code.

2022-07-25 15:25 UTC, mohanagy commented on tsconfig.json
> +}
you are defining the aliases , but I don't see any usage for them

2022-07-25 15:28 UTC, mohanagy commented on src/bin/index.ts
> +      contents[contentId].owedAccRevenue = revenue.times(new Big(1)
Sometimes, you use variables to define the value, and here you are passing the value directly.

2022-07-25 15:32 UTC, mohanagy commented on src/bin/index.ts
> +    const findLastReport = await Report.findOne({ order: [['id', 'DESC']] });
What is the point of not passing the transaction here and passing it to `const findAllDatabaseContents = Content.findAll({ transaction });` ?

2022-07-26 16:04 UTC, mohanagy commented on src/bin/index.ts
> +    contentReports.map(({
You are not assigning the result of the map function to any variable.
So I don't see any value of using the map or even returning the result

2022-07-26 16:06 UTC, mohanagy commented on src/bin/index.ts
> +    if (err instanceof Error) {
still there is no rollback for the transaction

2022-07-26 16:13 UTC, mohanagy commented on src/utilities/viewlift/requests/viewliftLogin.ts
> +interface LoginResponse {
it should be inside the interfaces folder

2022-07-27 05:04 UTC, mohanagy commented on src/utilities/watchesPerContent.ts
> +        tvodCount[contentId] = type === 'PAYMENT' ? tvodCount[contentId] + 1 : tvodCount[contentId] - 1;
constants like `PAYMENT` or `tvod` should be under constants folder

2022-07-27 14:41 UTC, mohanagy commented on src/bin/index.ts
> +    console.info('Fetching data from ViewLift API, it will take about', '\x1b[46m', '3 minutes', '\x1b[0m', 'please be patient...');
the message here says it takes about 3 mins
I just run the code, and it takes around 19.77s.and this confused me, is my internet that fast, or is there something wrong with the code?
![image](https://user-images.githubusercontent.com/11216054/181275876-817386fd-5418-4580-90a1-4a1fb42635b7.png)

2022-07-27 14:42 UTC, mohanagy commented on src/bin/index.ts
> +      offset: 0,
Are these default values?
In case Yes, then I believe you need to identify the default value in the arguments and not passing them here

2022-07-27 14:43 UTC, mohanagy commented on src/bin/index.ts
> +      offset: 0,
same here of the offset 0

2022-07-27 14:49 UTC, zaher-aa commented on src/bin/index.ts
> +    console.info('Fetching data from ViewLift API, it will take about', '\x1b[46m', '3 minutes', '\x1b[0m', 'please be patient...');
Make sure to build the database then run the code because if you already built the database and run the code then the code will check for the last report in the db and fetch viewlift data from the time you made the last report to the time you ran the code again.
So lets say you ran the code and a report was stored to the db, if you run the code again the time period for fetching viewlift data will be the time period from the last report to the time for the current run.
Hope this makes sence

2022-07-27 15:27 UTC, mohanagy commented on src/bin/index.ts
> +    console.info('Fetching data from ViewLift API, it will take about', '\x1b[46m', '3 minutes', '\x1b[0m', 'please be patient...');
makes sense, 
but I believe we need to log the window between the last report and the current time.
anyway 
I followed your instructions , I rebuild the database using `npm run build:db`
then `npm run dev`
and this was the result 
![image](https://user-images.githubusercontent.com/11216054/181287182-c36d39a8-5b03-4346-b1f3-b1790e13f993.png)

2022-07-27 16:08 UTC, mohanagy commented on src/bin/index.ts
> +    } = watchesPerContent(watchedStreams.filter(({ user }) => user), paymentsList, databaseContent);
I found you passing the iteration function as a parameter. And until now, I don't know what the point of doing this is?
actually, I see this is confusing

2022-07-27 16:11 UTC, mohanagy commented on src/database/index.ts
> +
Is it useful for the database to keep these lines here?
if there is a reason keep it , otherwise modularize it

2022-07-27 16:12 UTC, mohanagy commented on src/database/models/Content.ts
> +    },
createdBy,updatedBy,createdAt,updatedAt, these columns must comes at the end of the table

2022-07-27 16:16 UTC, mohanagy commented on src/database/models/ContentReport.ts
> +  'contentReport',
the table name must be `plural` -Add it even if sequelize is handling it-
also, the name must follow the snake case as a name convention

2022-07-27 16:17 UTC, mohanagy commented on src/database/models/Report.ts
> +}
All interfaces must be under one folder called interfaces

2022-07-27 16:20 UTC, mohanagy commented on src/database/models/Role.ts
> +  'role',
The table name should describe its content. And it should not be ambiguous.
`role` of what?

2022-07-27 16:22 UTC, mohanagy commented on src/database/models/Settings.ts
> +      type: DataTypes.STRING,
I believe that we agreed it should be JSON

2022-07-27 16:30 UTC, mohanagy commented on src/utilities/watchesPerContent.ts
> +    },
I beleive there is something wrong with the eslint or whatever you are using.
it doesn't make since to have one word in each line

2022-07-27 16:42 UTC, mohanagy commented on package.json
> +    "start": "cross-env NODE_ENV=development node ./dist/bin/",
I believe that the path is wrong

2022-07-27 16:43 UTC, mohanagy commented on package.json
> +    "start": "cross-env NODE_ENV=development node ./dist/bin/",
+ NODE_ENV = development ?
then where is the script command of the production ?

2022-07-27 16:56 UTC, mohanagy requested changes
Well done, what a great job.

A couple of notes I have:
1. I believe there is something wrong with the eslint. 
2. I left comments on something common, and I saw it a lot like interfaces 
3. I believe there is a package that missed `eslint-import-resolver-typescript.` Correct me if I'm wrong
4. test is missing
5. please modularize the code
6. replace the console with something better like .`Winston`
7. passing values as default values
8. passing iteration function 
9. I was not able to run the code after Zaher's advice so I don't know what the output of running the code is
10. test is missing

Otherwise, you did a great job, guys.

2022-07-27 18:42 UTC, Jood80 commented on src/bin/index.ts
> +    console.info('Fetching data from ViewLift API, it will take about', '\x1b[46m', '3 minutes', '\x1b[0m', 'please be patient...');
@mohanagy I had the same error earlier this week and the team suggested to `DISABLE TRIGGER` the tables manually in pgAdmin as a workaround solution to run it "back then at least":  
```sql
ALTER TABLE contents DISABLE TRIGGER ALL;
ALTER TABLE watches DISABLE TRIGGER ALL;
ALTER TABLE content_reports DISABLE TRIGGER ALL;
ALTER TABLE reports DISABLE TRIGGER ALL
```
And it worked on me. 
However, I'm trying to reproduce this error now, and it's so unfortunate that it doesn't like to show itself up again.
I believe sooner or later we'll have the honer to meet it while testing 🤞🏽

2022-07-27 19:10 UTC, zaher-aa commented on src/bin/index.ts
> +    console.info('Fetching data from ViewLift API, it will take about', '\x1b[46m', '3 minutes', '\x1b[0m', 'please be patient...');
Yeah, thats because I think you didn't run `npm run migrate:up` after building the database.
Since we are referencing the users table when inserting data to the contents table, there should be a user in the database with id: 1 and thats whats happening when running `npm run migrate:up`

2022-07-28 04:52 UTC, Ibrahim-Jarada commented on src/bin/index.ts
> +    } = watchesPerContent(watchedStreams.filter(({ user }) => user), paymentsList, databaseContent);
The platform allows a free preview of all shows for non-subscribers so they can watch a very short piece of the content for up to 60 seconds these users have a null value and should be omitted from watches in order not to affect the revenue share percentage

2022-07-28 05:18 UTC, Ibrahim-Jarada commented on src/utilities/watchesPerContent.ts
> +    },
I think it is not Eslint it is us.
I prefer using this way cause it's easier for me to temporarily disable a value by turning its line into a comment

2022-07-28 07:16 UTC, mohanagy commented on src/bin/index.ts
> +    console.info('Fetching data from ViewLift API, it will take about', '\x1b[46m', '3 minutes', '\x1b[0m', 'please be patient...');
I didn't run the migration because, as I remember, someone told me there was no need for the migration, 
am right?
Anyway, can we update the readme file and  include the instructions and all details about the project

2022-08-03 11:05 UTC, zaher-aa commented
> Well done, what a great job.
> 
> A couple of notes I have:
> 
> 1. I believe there is something wrong with the eslint.
> 2. I left comments on something common, and I saw it a lot like interfaces
> 3. I believe there is a package that missed `eslint-import-resolver-typescript.` Correct me if I'm wrong
> 4. test is missing
> 5. please modularize the code
> 6. replace the console with something better like .`Winston`
> 7. passing values as default values
> 8. passing iteration function
> 9. I was not able to run the code after Zaher's advice so I don't know what the output of running the code is
> 10. test is missing
> 
> Otherwise, you did a great job, guys.

## How to test it
```sh
1. npm run build:db
2. npm run dev
```
after that, Database models will be filled with viewlift data and our users data.

2022-08-16 17:21 UTC, mohanagy approved these changes

2022-08-16 17:26 UTC, merged