Hosted database models to npm
NextUp-comedy/calcs-nc pull request #38
Opened 2022-08-02 14:08 UTC by zaher-aa

npm link: https://www.npmjs.com/package/db-models-nc

2022-08-02 14:14 UTC, Jood80 approved these changes
Looking forward to celebrate the Alpha version of it!

2022-08-02 14:18 UTC, Ibrahim-Jarada requested changes
Remove database models from this repo

2022-08-03 06:48 UTC, zaher-aa commented
> Remove database models from this repo

Done

2022-08-03 06:50 UTC, Ibrahim-Jarada approved these changes

2022-08-03 10:53 UTC, RandSohail approved these changes

2022-08-03 10:55 UTC, merged